---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Create snmp community
      community.network.pn_snmp_community:
        state: "update"
        pn_community_string: "manitest"
        pn_community_type: "read-only"
