---
- name: Get port details and MAC-addresses
  hosts: Cisco
  gather_facts: false
  connection: local
  tasks:
    - name: Configure VLAN 100 on switch
      ios_config:
        lines:
          - vlan 234
          - name Marketing
