---
- name: Get port details and MAC-addresses
  hosts: Cisco
  gather_facts: false
  connection: local
  tasks:
     - name: Install python package
       ansible.builtin.pip:
         name: ansible-pylibssh
       delegate_to: localhost
    - name: show version
      ios_command:
        commands: show version
