---
- name: Verify interface status on Cisco switches
  hosts: Cisco
  gather_facts: no
  tasks:
      - name: show run
        ios_command:
          commands:
          - show ip interface brief
        register: config
        
      - name: Parse the output
        debug:
          msg: "{{ config }}"
